# Generated by Django 3.2.4 on 2021-06-17 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible', models.BooleanField(verbose_name='Является ли админом')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notify_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст нотификации')),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Task_priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_priority', models.CharField(choices=[('blocker', 'Blocker'), ('critical', 'Critical'), ('major', 'Major'), ('medium', 'Medium'), ('minor', 'Minor'), ('trivial', 'Trivial')], max_length=10)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('text', models.TextField(verbose_name='Текст задачи')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('on_test', 'On test'), ('need_to_merge', 'Need to merge')], default='open', max_length=15)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.task_priority')),
                ('responsible_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.responsible')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('employe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.employe')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
        ),
    ]
