# Generated by Django 3.2.4 on 2021-06-17 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_responsible_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 22, 20, 33, 926886, tzinfo=utc), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('on_test', 'On test'), ('need_to_merge', 'Need to merge'), ('developing', 'Developing')], default='open', max_length=15),
        ),
    ]
